### ISSUE TITLE
/wp-admin/admin.php?page=mbdb_migrate can not access

### ISSUE THREAD

**Issue by almas** [christiespeich/Mooberry-Book-Manager#28]
When I click buttons migrate then it does not access. 

/wp-admin/admin.php?page=mbdb_migrate
/wp-admin/admin.php?page=mbdb_migrate_grids

**"Sorry, you are not allowed to access this page."**

Can someone help me?

**Comment by almas** [comment]
I just migrated:

Changed line class-mbm-core-settings.php 76-81 to below:

		// $current_version = get_option(MBDB_PLUGIN_VERSION_KEY);
		// if (version_compare($current_version, '2.4.4', '>') && version_compare($current_version, '4.0', '<')) {
			$this->pages['mbdb_migrate'] = array ( 'page_title'	=>	__('Mooberry Book Manager v3.0 Data Migration', 'mooberry-book-manager'),
												'menu_title'	=>	__('Migrate Data', 'mooberry-book-manager')
												);
		// }


And also changed line 173 to:
	$success = MBDB()->books_db->import();

Because there was error in 173.

**Comment by christiespeich** [comment]
I am so sorry that I never replied to this.  I am just seeing it now. I'm going to close it as I assume you've either fixed the issue or are no longer using the plugin.
If you still need help, let me know and I'll look again.
