### ISSUE TITLE
Fatal Error after activating plugin

### ISSUE THREAD

**Issue by pobn** [christiespeich/Mooberry-Book-Manager#29]
Hi, 
Thanks for this useful plugin. I have used the old version before updating. Everything was ok. After updating to last version, this error is displayed:

> Fatal error: Uncaught ArgumentCountError: Too few arguments to function MBDB_Books::get_ordered_selection(), 3 passed in /../wp-content/plugins/mooberry-book-manager/includes/depreciated-functions.php on line 304 and exactly 5 expected in /../wp-content/plugins/mooberry-book-manager/includes/class-mbdb-books.php:19 Stack trace: #0 /../wp-content/plugins/mooberry-book-manager/includes/depreciated-functions.php(304): MBDB_Books->get_ordered_selection('all', NULL, 'titleA') #1 /../wp-content/plugins/mooberry-book-manager/includes/updates.php(344): mbdb_get_books_list('all', NULL, 'title', 'ASC', NULL, NULL, NULL) #2 /../wp-content/plugins/mooberry-book-manager/includes/updates.php(219): mbdb_migrate_post_tags() #3 /../wp-content/plugins/mooberry-book-manager/includes/updates.php(19): mbdb_upgrade_to_2_0() #4 /../wp-includes/class-wp-hook.php(298): mbdb_ in /../wp-content/plugins/mooberry-book-manager/includes/class-mbdb-books.php on line 19

I have deleted all old data, but the Problem is still there. I have installed also github version, but nothing happened. Could you help me with it. Thanks.

**Comment by christiespeich** [comment]
I am so sorry that I never replied to this. I am just seeing it now. I'm going to close it as I assume you've either fixed the issue or are no longer using the plugin.
If you still need help, let me know and I'll look again.
