### ISSUE TITLE
Shortcodes for Mooberry books and book grids

### ISSUE THREAD

**Issue by joeytwiddle** [christiespeich/Mooberry-Book-Manager#8]
Shortcodes have been [suggested](http://docs.layerswp.com/forums/question/content-injected-via-the_content-filter-should-only-appear-in-one-panel/) as one possible solution to a problem we [discussed](https://wordpress.org/support/topic/avoid-adding-to-secondary-blocks-created-on-the-page-eg-with-register_sidebar) last year of themes which trigger `the_content` multiple times per page.

It looks like you have a simple `mbdb_tax_grid` shortcode already! I hacked [this line](https://github.com/joeytwiddle/Mooberry-Book-Manager/commit/d2dc976a9495624c8415f43f4f54dfd6d517124c) to display a grid on the front page. Yay it works for us!

At some point I would like it to display a limited number of books, only those from a specified category (tax/term?), and perhaps randomise the order too. I will let you know if I manage to do any of those things. (I am not experienced in PHP or WP.) Please let me know if you make any inroads into this feature, or have any suggestions for me. Cheers!

**Comment by christiespeich** [comment]
Hmmm...not sure why you need a work around to put a grid on the front page? A Book Grid can be added to any page, including the front page. Maybe I don't understand what you are trying to do?

**Comment by joeytwiddle** [comment]
Why did I need to use a shortcode? Because we are using LayersWP. If I check the box "Show book grid on this page" then we actually get three book grids, because LayersWP triggers `the_content` three times!

Why did I hack the code? I just wanted to display a book grid of all books, without specifying a term or a taxonomy. At the moment, without a term and a taxonomy, the shortcode displays nothing.

But actually that was only really for testing. Eventually we will want to filter the books.

I just created this issue as a communication channel. If you make, or plan, any changes to the shortcodes, please let me know here, and I will do the same.

**Comment by christiespeich** [comment]
Ah, gotcha. Sorry, I should have clicked the link in your first message. I blame being sick! :-P

Version 3.0 is going out tonight or tomorrow so not something I can add for that, but I can definitely see about it in 3.1.

Just off the top of my head, I'm wondering where the best place for actually creating the shortcode is? It could be a "hidden" feature that you could type in manually, but I think making it pull from the options set on the page and using a shortcode to display it could help with other themes as well. That's why book pages and tax grids are now shortcodes. Maybe there's another hook to use to grab the parameters?

**Comment by joeytwiddle** [comment]
Congrats on V3! :birthday: And get well soon. :wine_glass:

**Comment by christiespeich** [comment]
I just had a thought....for you to get the shortcode working with all the parameters, what if you changed that line 63 to this:

`return mbdb_bookgrid_content();`

I think should pull the parameters you can set on the page and display the book grid you are looking for.

**Comment by christiespeich** [comment]
I haven't tested, and it's a workaround until there's a proper book grid shortcode with parameters but it might be an easy fix for now.

**Comment by joeytwiddle** [comment]
Sorry, it took me a while to get around to testing that. It works very nicely. Thanks!

<strike>We would like to make a donation. If that possible? If so, how?</strike> Never mind I found it!

**Comment by christiespeich** [comment]
Glad to hear that is working for you!

I am neck-deep in making MBM compatible with multi-site and getting ver 3 re-rolled out. I'll work on shortcode params in a later update, maybe 3.2?

I did add a donation link to version 3 -- is that what you found?  Thanks so much!

**Comment by christiespeich** [comment]
I realize this is old, and maybe you've already seen it, but the current version of MBM now fully supports shortcodes for Book Grids with a UI.
